[WIP] - Login, Register, UserList - API Calls and Display
kconde2/vote-app pull request #33
Opened 2020-01-13 00:43 UTC by dachic

- [ ] Login : Works

- [ ] Register : API call returns a "Bad Request error 400" debuging...

- [ ] Userlist : Working but you have to put the JWT in the code yourself - context.state.currentUser returning null in *getUsers* method but working in *login* method...

2020-01-13 06:38 UTC, kconde2 commented
J'ai regardé vaquement
le `node_modules` et le `package-lock.json` à la racine du projet ne servent à rien

2020-01-13 06:49 UTC, kconde2 requested changes

2020-01-13 06:49 UTC, kconde2 commented on app/src/store/index.js
> +          "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfbGV2ZWwiOjEsImV4cCI6MTU3ODg3ODUzNywib3JpZ19pYXQiOjE1Nzg4NzQ5MzcsInV1aWQiOiI4YTM1YzMwYi00NmVkLTQyN2QtYWU4Yi1jNzQ3OTI
Je sais que n'a pas encore fini mais pour ça, faudrait ajouter le token en local storage pour ensuite l'utiliser dans toutes les autres requêtes en l'incluant dans le header de tous les calls api axios comme ceci : `axios.defaults.headers.common.Authorization = `Bearer ${authToken}`;`

Voici des références à ce que je veux dire : 
- https://github.com/axios/axios#config-defaults
- https://stackoverflow.com/questions/54652685/how-can-i-store-a-jwt-in-cookies-using-axios

2020-01-24 22:33 UTC, AmeenaAZIZ approved these changes

2020-01-25 19:48 UTC, kconde2 approved these changes

2020-01-25 19:49 UTC, merged